### ISSUE TITLE
Do compiled wkhtmltopdf binaries still require wkhtmltopdf in the system path?

### ISSUE THREAD

**Issue by olup** [anowell/wkhtmltopdf-rs#13]
This is a basic question but I wondered : 
I understand I need Wkhtmltopdf present in the system wile I build the app. Does it mean the resulting build can be ditributed on some host that don't have wkhtmltopdf installed as it will be buit into my own binaries ?

**Comment by craigmayhew** [comment]
Hi @olup

The resulting build will error if run on a system without wkhtmltopdf present. To prove this I compiled a test app with the wkhtmltopdf-rs dependency on a system where libwkhtmltox was installed. I then tried to run the resulting binary on a different system (same OS) and it wasn't able to run.

```
./target/release/pdf_test
./target/release/pdf_test: error while loading shared libraries: libwkhtmltox.so.0: cannot open shared object file: No such file or directory
```

**Comment by olup** [comment]
Thanks a lot for providing this test !
